package basos.xe.data.dao;

import java.util.List;

import org.apache.ibatis.annotations.Select;

import basos.xe.data.entity.DealLastState;

/** Маппинг сделок из мвью MV_DEALS_LAST_STATE на сущность DealLastState. */
public interface DealLastStateMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MV_DEALS_LAST_STATE
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	DealLastState selectByPrimaryKey(Integer idDeal);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MV_DEALS_LAST_STATE
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	List<DealLastState> selectAll();
	
    
// TODO: сделать пейджирование и RowBound
	/** Поиск сделок по заёмщику (FK). */
    List<DealLastState> selectByClnId(Integer clnId);
    
    /** Поиск сделок по СПР (FK) */
    List<DealLastState> selectByRsubjId(Integer rsubjId);
    
    /** Общее количество строк (сделок) в таблице. */
    @Select("select count(*) cnt from MV_DEALS_LAST_STATE")
    int rowCount();
}