package basos.xe.data.dao;

import java.util.List;

import org.apache.ibatis.annotations.Select;

import basos.xe.data.entity.TrancheLastState;


/** Маппинг сделок из мвью MV_TRANCHES_LAST_STATE на сущность TrancheLastState. */
public interface TrancheLastStateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_TRANCHES_LAST_STATE
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    TrancheLastState selectByPrimaryKey(Integer idDeal);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_TRANCHES_LAST_STATE
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    List<TrancheLastState> selectAll();
    
    
// TODO: сделать пейджирование и RowBound
    
    /** Поиск траншей по заёмщику (FK SubjSumm.cln_id). */
    List<TrancheLastState> selectByClnId(Integer clnId);
    
    /** Поиск траншей по СПР (FK SubjSumm.rsubj_id). */
    List<TrancheLastState> selectByRsubjId(Integer rsubjId);
    
    /** Поиск траншей по рамке (FK DealLastState.idDeal). */
    List<TrancheLastState> selectByIdParent(Integer idParent);
    
    /** Общее количество строк (траншей) в таблице. */
    @Select("select count(*) cnt from MV_TRANCHES_LAST_STATE")
    int rowCount();

} // public interface TrancheLastStateMapper 