package basos.xe.data.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;
import java.util.Comparator;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


/** Entity class "все сделки (без траншей, т.е. кредиты/гарантии и линии) из последнего среза с остатками", обёртываемый в GridData для использования в гриде/листбоксе.
 * RULE: все приватные нестатические поля доменного объекта класс beanClass должны относиться к полям данных.
 * Метод {@link #getPkMap()} - часть статического интерфейса.
 */
public class DealLastState implements Serializable, Comparable<DealLastState> {
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.IDDEAL
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private Integer idDeal;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.IDPARENT
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private Integer idParent;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.DD_REST
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private Date ddRest;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.BAL_TYPE
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private String balType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.PROD_TYPE
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private String prodType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.CLN_ID
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private Integer clnId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.CLN_NAME
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private String clnName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.RSUBJ_ID
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private Integer rsubjId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.RSUBJ_NAME
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private String rsubjName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.DOG_NUM
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private String dogNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.TR_DOG_NUM
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private String trDogNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.DGVR_DATE
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private Date dgvrDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.DBEGIN
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private Date dbegin;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.DEND
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private Date dend;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.DDEALCLOSE
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private Date ddealClose;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.DAYS
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private Integer days;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.YDUR
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private BigDecimal ydur;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.DGVR_CUR
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private String dgvrCur;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.DGVR_SUM
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private BigDecimal dgvrSum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.DGVR_SUM_USD
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private BigDecimal dgvrSumUsd;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.PERC
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private BigDecimal perc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.PERC_KIND
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private String percKind;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.FOND_RATE
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private BigDecimal fondRate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.RISKADD_RATE
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private BigDecimal riskaddRate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.MRASH_RATE
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private BigDecimal mrashRate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.GR_OD
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private String grOd;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.GR_PERC
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private String grPerc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.AR_TYPE
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private String arType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.SUM_PROVISION_USD
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private BigDecimal sumProvisionUsd;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.SUM_MSFO_CHARGEOFF
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private BigDecimal sumMsfoChargeoff;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.PROD_VAR
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private String prodVar;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.PROD_GR
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private String prodGr;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.PROD_GOAL
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private String prodGoal;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.ID_REQ_ZIP_KK
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private Integer idReqZipKk;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.LS_KK
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private Integer lsKk;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.IDLIMIT
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private Integer idLimit;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.COMMITTEE_NAME
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private String committeeName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.DECISION_NUMBER
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private String decisionNumber;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.DECISION_DATE
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private Date decisionDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.FLG_312P
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private String flg312p;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.DEP
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private String dep;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.DEP_FIO
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private String depFio;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.KBE
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private String kbe;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.KBE_FIO
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private String kbeFio;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.IS_SME_DEAL
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private Boolean isSmeDeal;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MV_DEALS_LAST_STATE.LMCP_ROWID
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	private String lmcpRowId;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MV_DEALS_LAST_STATE
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public DealLastState(Integer idDeal, Integer idParent, Date ddRest, String balType, String prodType, Integer clnId,
			String clnName, Integer rsubjId, String rsubjName, String dogNum, String trDogNum, Date dgvrDate,
			Date dbegin, Date dend, Date ddealClose, Integer days, BigDecimal ydur, String dgvrCur, BigDecimal dgvrSum,
			BigDecimal dgvrSumUsd, BigDecimal perc, String percKind, BigDecimal fondRate, BigDecimal riskaddRate,
			BigDecimal mrashRate, String grOd, String grPerc, String arType, BigDecimal sumProvisionUsd,
			BigDecimal sumMsfoChargeoff, String prodVar, String prodGr, String prodGoal, Integer idReqZipKk,
			Integer lsKk, Integer idLimit, String committeeName, String decisionNumber, Date decisionDate,
			String flg312p, String dep, String depFio, String kbe, String kbeFio, Boolean isSmeDeal, String lmcpRowId) {
		this.idDeal = idDeal;
		this.idParent = idParent;
		this.ddRest = ddRest;
		this.balType = balType;
		this.prodType = prodType;
		this.clnId = clnId;
		this.clnName = clnName;
		this.rsubjId = rsubjId;
		this.rsubjName = rsubjName;
		this.dogNum = dogNum;
		this.trDogNum = trDogNum;
		this.dgvrDate = dgvrDate;
		this.dbegin = dbegin;
		this.dend = dend;
		this.ddealClose = ddealClose;
		this.days = days;
		this.ydur = ydur;
		this.dgvrCur = dgvrCur;
		this.dgvrSum = dgvrSum;
		this.dgvrSumUsd = dgvrSumUsd;
		this.perc = perc;
		this.percKind = percKind;
		this.fondRate = fondRate;
		this.riskaddRate = riskaddRate;
		this.mrashRate = mrashRate;
		this.grOd = grOd;
		this.grPerc = grPerc;
		this.arType = arType;
		this.sumProvisionUsd = sumProvisionUsd;
		this.sumMsfoChargeoff = sumMsfoChargeoff;
		this.prodVar = prodVar;
		this.prodGr = prodGr;
		this.prodGoal = prodGoal;
		this.idReqZipKk = idReqZipKk;
		this.lsKk = lsKk;
		this.idLimit = idLimit;
		this.committeeName = committeeName;
		this.decisionNumber = decisionNumber;
		this.decisionDate = decisionDate;
		this.flg312p = flg312p;
		this.dep = dep;
		this.depFio = depFio;
		this.kbe = kbe;
		this.kbeFio = kbeFio;
		this.isSmeDeal = isSmeDeal;
		this.lmcpRowId = lmcpRowId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.IDDEAL
	 * @return  the value of MV_DEALS_LAST_STATE.IDDEAL
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public Integer getIdDeal() {
		return idDeal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.IDDEAL
	 * @param idDeal  the value for MV_DEALS_LAST_STATE.IDDEAL
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setIdDeal(Integer idDeal) {
		this.idDeal = idDeal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.IDPARENT
	 * @return  the value of MV_DEALS_LAST_STATE.IDPARENT
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public Integer getIdParent() {
		return idParent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.IDPARENT
	 * @param idParent  the value for MV_DEALS_LAST_STATE.IDPARENT
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setIdParent(Integer idParent) {
		this.idParent = idParent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.DD_REST
	 * @return  the value of MV_DEALS_LAST_STATE.DD_REST
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public Date getDdRest() {
		return ddRest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.DD_REST
	 * @param ddRest  the value for MV_DEALS_LAST_STATE.DD_REST
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setDdRest(Date ddRest) {
		this.ddRest = ddRest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.BAL_TYPE
	 * @return  the value of MV_DEALS_LAST_STATE.BAL_TYPE
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public String getBalType() {
		return balType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.BAL_TYPE
	 * @param balType  the value for MV_DEALS_LAST_STATE.BAL_TYPE
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setBalType(String balType) {
		this.balType = balType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.PROD_TYPE
	 * @return  the value of MV_DEALS_LAST_STATE.PROD_TYPE
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public String getProdType() {
		return prodType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.PROD_TYPE
	 * @param prodType  the value for MV_DEALS_LAST_STATE.PROD_TYPE
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setProdType(String prodType) {
		this.prodType = prodType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.CLN_ID
	 * @return  the value of MV_DEALS_LAST_STATE.CLN_ID
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public Integer getClnId() {
		return clnId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.CLN_ID
	 * @param clnId  the value for MV_DEALS_LAST_STATE.CLN_ID
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setClnId(Integer clnId) {
		this.clnId = clnId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.CLN_NAME
	 * @return  the value of MV_DEALS_LAST_STATE.CLN_NAME
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public String getClnName() {
		return clnName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.CLN_NAME
	 * @param clnName  the value for MV_DEALS_LAST_STATE.CLN_NAME
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setClnName(String clnName) {
		this.clnName = clnName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.RSUBJ_ID
	 * @return  the value of MV_DEALS_LAST_STATE.RSUBJ_ID
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public Integer getRsubjId() {
		return rsubjId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.RSUBJ_ID
	 * @param rsubjId  the value for MV_DEALS_LAST_STATE.RSUBJ_ID
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setRsubjId(Integer rsubjId) {
		this.rsubjId = rsubjId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.RSUBJ_NAME
	 * @return  the value of MV_DEALS_LAST_STATE.RSUBJ_NAME
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public String getRsubjName() {
		return rsubjName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.RSUBJ_NAME
	 * @param rsubjName  the value for MV_DEALS_LAST_STATE.RSUBJ_NAME
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setRsubjName(String rsubjName) {
		this.rsubjName = rsubjName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.DOG_NUM
	 * @return  the value of MV_DEALS_LAST_STATE.DOG_NUM
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public String getDogNum() {
		return dogNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.DOG_NUM
	 * @param dogNum  the value for MV_DEALS_LAST_STATE.DOG_NUM
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setDogNum(String dogNum) {
		this.dogNum = dogNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.TR_DOG_NUM
	 * @return  the value of MV_DEALS_LAST_STATE.TR_DOG_NUM
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public String getTrDogNum() {
		return trDogNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.TR_DOG_NUM
	 * @param trDogNum  the value for MV_DEALS_LAST_STATE.TR_DOG_NUM
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setTrDogNum(String trDogNum) {
		this.trDogNum = trDogNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.DGVR_DATE
	 * @return  the value of MV_DEALS_LAST_STATE.DGVR_DATE
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public Date getDgvrDate() {
		return dgvrDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.DGVR_DATE
	 * @param dgvrDate  the value for MV_DEALS_LAST_STATE.DGVR_DATE
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setDgvrDate(Date dgvrDate) {
		this.dgvrDate = dgvrDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.DBEGIN
	 * @return  the value of MV_DEALS_LAST_STATE.DBEGIN
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public Date getDbegin() {
		return dbegin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.DBEGIN
	 * @param dbegin  the value for MV_DEALS_LAST_STATE.DBEGIN
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setDbegin(Date dbegin) {
		this.dbegin = dbegin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.DEND
	 * @return  the value of MV_DEALS_LAST_STATE.DEND
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public Date getDend() {
		return dend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.DEND
	 * @param dend  the value for MV_DEALS_LAST_STATE.DEND
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setDend(Date dend) {
		this.dend = dend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.DDEALCLOSE
	 * @return  the value of MV_DEALS_LAST_STATE.DDEALCLOSE
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public Date getDdealClose() {
		return ddealClose;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.DDEALCLOSE
	 * @param ddealClose  the value for MV_DEALS_LAST_STATE.DDEALCLOSE
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setDdealClose(Date ddealClose) {
		this.ddealClose = ddealClose;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.DAYS
	 * @return  the value of MV_DEALS_LAST_STATE.DAYS
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public Integer getDays() {
		return days;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.DAYS
	 * @param days  the value for MV_DEALS_LAST_STATE.DAYS
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setDays(Integer days) {
		this.days = days;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.YDUR
	 * @return  the value of MV_DEALS_LAST_STATE.YDUR
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public BigDecimal getYdur() {
		return ydur;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.YDUR
	 * @param ydur  the value for MV_DEALS_LAST_STATE.YDUR
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setYdur(BigDecimal ydur) {
		this.ydur = ydur;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.DGVR_CUR
	 * @return  the value of MV_DEALS_LAST_STATE.DGVR_CUR
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public String getDgvrCur() {
		return dgvrCur;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.DGVR_CUR
	 * @param dgvrCur  the value for MV_DEALS_LAST_STATE.DGVR_CUR
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setDgvrCur(String dgvrCur) {
		this.dgvrCur = dgvrCur;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.DGVR_SUM
	 * @return  the value of MV_DEALS_LAST_STATE.DGVR_SUM
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public BigDecimal getDgvrSum() {
		return dgvrSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.DGVR_SUM
	 * @param dgvrSum  the value for MV_DEALS_LAST_STATE.DGVR_SUM
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setDgvrSum(BigDecimal dgvrSum) {
		this.dgvrSum = dgvrSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.DGVR_SUM_USD
	 * @return  the value of MV_DEALS_LAST_STATE.DGVR_SUM_USD
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public BigDecimal getDgvrSumUsd() {
		return dgvrSumUsd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.DGVR_SUM_USD
	 * @param dgvrSumUsd  the value for MV_DEALS_LAST_STATE.DGVR_SUM_USD
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setDgvrSumUsd(BigDecimal dgvrSumUsd) {
		this.dgvrSumUsd = dgvrSumUsd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.PERC
	 * @return  the value of MV_DEALS_LAST_STATE.PERC
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public BigDecimal getPerc() {
		return perc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.PERC
	 * @param perc  the value for MV_DEALS_LAST_STATE.PERC
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setPerc(BigDecimal perc) {
		this.perc = perc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.PERC_KIND
	 * @return  the value of MV_DEALS_LAST_STATE.PERC_KIND
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public String getPercKind() {
		return percKind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.PERC_KIND
	 * @param percKind  the value for MV_DEALS_LAST_STATE.PERC_KIND
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setPercKind(String percKind) {
		this.percKind = percKind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.FOND_RATE
	 * @return  the value of MV_DEALS_LAST_STATE.FOND_RATE
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public BigDecimal getFondRate() {
		return fondRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.FOND_RATE
	 * @param fondRate  the value for MV_DEALS_LAST_STATE.FOND_RATE
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setFondRate(BigDecimal fondRate) {
		this.fondRate = fondRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.RISKADD_RATE
	 * @return  the value of MV_DEALS_LAST_STATE.RISKADD_RATE
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public BigDecimal getRiskaddRate() {
		return riskaddRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.RISKADD_RATE
	 * @param riskaddRate  the value for MV_DEALS_LAST_STATE.RISKADD_RATE
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setRiskaddRate(BigDecimal riskaddRate) {
		this.riskaddRate = riskaddRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.MRASH_RATE
	 * @return  the value of MV_DEALS_LAST_STATE.MRASH_RATE
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public BigDecimal getMrashRate() {
		return mrashRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.MRASH_RATE
	 * @param mrashRate  the value for MV_DEALS_LAST_STATE.MRASH_RATE
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setMrashRate(BigDecimal mrashRate) {
		this.mrashRate = mrashRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.GR_OD
	 * @return  the value of MV_DEALS_LAST_STATE.GR_OD
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public String getGrOd() {
		return grOd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.GR_OD
	 * @param grOd  the value for MV_DEALS_LAST_STATE.GR_OD
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setGrOd(String grOd) {
		this.grOd = grOd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.GR_PERC
	 * @return  the value of MV_DEALS_LAST_STATE.GR_PERC
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public String getGrPerc() {
		return grPerc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.GR_PERC
	 * @param grPerc  the value for MV_DEALS_LAST_STATE.GR_PERC
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setGrPerc(String grPerc) {
		this.grPerc = grPerc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.AR_TYPE
	 * @return  the value of MV_DEALS_LAST_STATE.AR_TYPE
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public String getArType() {
		return arType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.AR_TYPE
	 * @param arType  the value for MV_DEALS_LAST_STATE.AR_TYPE
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setArType(String arType) {
		this.arType = arType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.SUM_PROVISION_USD
	 * @return  the value of MV_DEALS_LAST_STATE.SUM_PROVISION_USD
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public BigDecimal getSumProvisionUsd() {
		return sumProvisionUsd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.SUM_PROVISION_USD
	 * @param sumProvisionUsd  the value for MV_DEALS_LAST_STATE.SUM_PROVISION_USD
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setSumProvisionUsd(BigDecimal sumProvisionUsd) {
		this.sumProvisionUsd = sumProvisionUsd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.SUM_MSFO_CHARGEOFF
	 * @return  the value of MV_DEALS_LAST_STATE.SUM_MSFO_CHARGEOFF
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public BigDecimal getSumMsfoChargeoff() {
		return sumMsfoChargeoff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.SUM_MSFO_CHARGEOFF
	 * @param sumMsfoChargeoff  the value for MV_DEALS_LAST_STATE.SUM_MSFO_CHARGEOFF
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setSumMsfoChargeoff(BigDecimal sumMsfoChargeoff) {
		this.sumMsfoChargeoff = sumMsfoChargeoff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.PROD_VAR
	 * @return  the value of MV_DEALS_LAST_STATE.PROD_VAR
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public String getProdVar() {
		return prodVar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.PROD_VAR
	 * @param prodVar  the value for MV_DEALS_LAST_STATE.PROD_VAR
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setProdVar(String prodVar) {
		this.prodVar = prodVar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.PROD_GR
	 * @return  the value of MV_DEALS_LAST_STATE.PROD_GR
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public String getProdGr() {
		return prodGr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.PROD_GR
	 * @param prodGr  the value for MV_DEALS_LAST_STATE.PROD_GR
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setProdGr(String prodGr) {
		this.prodGr = prodGr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.PROD_GOAL
	 * @return  the value of MV_DEALS_LAST_STATE.PROD_GOAL
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public String getProdGoal() {
		return prodGoal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.PROD_GOAL
	 * @param prodGoal  the value for MV_DEALS_LAST_STATE.PROD_GOAL
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setProdGoal(String prodGoal) {
		this.prodGoal = prodGoal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.ID_REQ_ZIP_KK
	 * @return  the value of MV_DEALS_LAST_STATE.ID_REQ_ZIP_KK
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public Integer getIdReqZipKk() {
		return idReqZipKk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.ID_REQ_ZIP_KK
	 * @param idReqZipKk  the value for MV_DEALS_LAST_STATE.ID_REQ_ZIP_KK
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setIdReqZipKk(Integer idReqZipKk) {
		this.idReqZipKk = idReqZipKk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.LS_KK
	 * @return  the value of MV_DEALS_LAST_STATE.LS_KK
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public Integer getLsKk() {
		return lsKk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.LS_KK
	 * @param lsKk  the value for MV_DEALS_LAST_STATE.LS_KK
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setLsKk(Integer lsKk) {
		this.lsKk = lsKk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.IDLIMIT
	 * @return  the value of MV_DEALS_LAST_STATE.IDLIMIT
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public Integer getIdLimit() {
		return idLimit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.IDLIMIT
	 * @param idLimit  the value for MV_DEALS_LAST_STATE.IDLIMIT
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setIdLimit(Integer idLimit) {
		this.idLimit = idLimit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.COMMITTEE_NAME
	 * @return  the value of MV_DEALS_LAST_STATE.COMMITTEE_NAME
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public String getCommitteeName() {
		return committeeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.COMMITTEE_NAME
	 * @param committeeName  the value for MV_DEALS_LAST_STATE.COMMITTEE_NAME
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setCommitteeName(String committeeName) {
		this.committeeName = committeeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.DECISION_NUMBER
	 * @return  the value of MV_DEALS_LAST_STATE.DECISION_NUMBER
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public String getDecisionNumber() {
		return decisionNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.DECISION_NUMBER
	 * @param decisionNumber  the value for MV_DEALS_LAST_STATE.DECISION_NUMBER
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setDecisionNumber(String decisionNumber) {
		this.decisionNumber = decisionNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.DECISION_DATE
	 * @return  the value of MV_DEALS_LAST_STATE.DECISION_DATE
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public Date getDecisionDate() {
		return decisionDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.DECISION_DATE
	 * @param decisionDate  the value for MV_DEALS_LAST_STATE.DECISION_DATE
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setDecisionDate(Date decisionDate) {
		this.decisionDate = decisionDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.FLG_312P
	 * @return  the value of MV_DEALS_LAST_STATE.FLG_312P
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public String getFlg312p() {
		return flg312p;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.FLG_312P
	 * @param flg312p  the value for MV_DEALS_LAST_STATE.FLG_312P
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setFlg312p(String flg312p) {
		this.flg312p = flg312p;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.DEP
	 * @return  the value of MV_DEALS_LAST_STATE.DEP
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public String getDep() {
		return dep;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.DEP
	 * @param dep  the value for MV_DEALS_LAST_STATE.DEP
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setDep(String dep) {
		this.dep = dep;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.DEP_FIO
	 * @return  the value of MV_DEALS_LAST_STATE.DEP_FIO
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public String getDepFio() {
		return depFio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.DEP_FIO
	 * @param depFio  the value for MV_DEALS_LAST_STATE.DEP_FIO
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setDepFio(String depFio) {
		this.depFio = depFio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.KBE
	 * @return  the value of MV_DEALS_LAST_STATE.KBE
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public String getKbe() {
		return kbe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.KBE
	 * @param kbe  the value for MV_DEALS_LAST_STATE.KBE
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setKbe(String kbe) {
		this.kbe = kbe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.KBE_FIO
	 * @return  the value of MV_DEALS_LAST_STATE.KBE_FIO
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public String getKbeFio() {
		return kbeFio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.KBE_FIO
	 * @param kbeFio  the value for MV_DEALS_LAST_STATE.KBE_FIO
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setKbeFio(String kbeFio) {
		this.kbeFio = kbeFio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.IS_SME_DEAL
	 * @return  the value of MV_DEALS_LAST_STATE.IS_SME_DEAL
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public Boolean getIsSmeDeal() {
		return isSmeDeal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.IS_SME_DEAL
	 * @param isSmeDeal  the value for MV_DEALS_LAST_STATE.IS_SME_DEAL
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setIsSmeDeal(Boolean isSmeDeal) {
		this.isSmeDeal = isSmeDeal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MV_DEALS_LAST_STATE.LMCP_ROWID
	 * @return  the value of MV_DEALS_LAST_STATE.LMCP_ROWID
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public String getLmcpRowId() {
		return lmcpRowId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MV_DEALS_LAST_STATE.LMCP_ROWID
	 * @param lmcpRowId  the value for MV_DEALS_LAST_STATE.LMCP_ROWID
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	public void setLmcpRowId(String lmcpRowId) {
		this.lmcpRowId = lmcpRowId;
	}

// см. toString в одну строку: ReflectionToStringBuilder.toString(this, ToStringStyle.MULTI_LINE_STYLE)
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MV_DEALS_LAST_STATE
	 * @mbg.generated  Mon Feb 13 18:05:48 MSK 2017
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", idDeal=").append(idDeal);
		sb.append(", idParent=").append(idParent);
		sb.append(", ddRest=").append(ddRest);
		sb.append(", balType=").append(balType);
		sb.append(", prodType=").append(prodType);
		sb.append(", clnId=").append(clnId);
		sb.append(", clnName=").append(clnName);
		sb.append(", rsubjId=").append(rsubjId);
		sb.append(", rsubjName=").append(rsubjName);
		sb.append(", dogNum=").append(dogNum);
		sb.append(", trDogNum=").append(trDogNum);
		sb.append(", dgvrDate=").append(dgvrDate);
		sb.append(", dbegin=").append(dbegin);
		sb.append(", dend=").append(dend);
		sb.append(", ddealClose=").append(ddealClose);
		sb.append(", days=").append(days);
		sb.append(", ydur=").append(ydur);
		sb.append(", dgvrCur=").append(dgvrCur);
		sb.append(", dgvrSum=").append(dgvrSum);
		sb.append(", dgvrSumUsd=").append(dgvrSumUsd);
		sb.append(", perc=").append(perc);
		sb.append(", percKind=").append(percKind);
		sb.append(", fondRate=").append(fondRate);
		sb.append(", riskaddRate=").append(riskaddRate);
		sb.append(", mrashRate=").append(mrashRate);
		sb.append(", grOd=").append(grOd);
		sb.append(", grPerc=").append(grPerc);
		sb.append(", arType=").append(arType);
		sb.append(", sumProvisionUsd=").append(sumProvisionUsd);
		sb.append(", sumMsfoChargeoff=").append(sumMsfoChargeoff);
		sb.append(", prodVar=").append(prodVar);
		sb.append(", prodGr=").append(prodGr);
		sb.append(", prodGoal=").append(prodGoal);
		sb.append(", idReqZipKk=").append(idReqZipKk);
		sb.append(", lsKk=").append(lsKk);
		sb.append(", idLimit=").append(idLimit);
		sb.append(", committeeName=").append(committeeName);
		sb.append(", decisionNumber=").append(decisionNumber);
		sb.append(", decisionDate=").append(decisionDate);
		sb.append(", flg312p=").append(flg312p);
		sb.append(", dep=").append(dep);
		sb.append(", depFio=").append(depFio);
		sb.append(", kbe=").append(kbe);
		sb.append(", kbeFio=").append(kbeFio);
		sb.append(", isSmeDeal=").append(isSmeDeal);
		sb.append(", lmcpRowId=").append(lmcpRowId);
		sb.append("]");
		return sb.toString();
	}

	/** RULE: конструктор по умолчанию генерит тестовые данные. */
// !!! MyBatis-generator генерит свой пустой безаргументный конструктор с опцией generatorConfiguration.context.table.constructorBased !!!
	public DealLastState() {
	} // no-arg constructor of mock object

	private static final long serialVersionUID = -1000167831102430929L;

	private static final Logger logger = LoggerFactory.getLogger(DealLastState.class);
	
    public static long getSerialVersionUID() {
		return serialVersionUID;
	}
    
// (вызывается из hashCode() грид-обёртки GridData) для списка объектов хэшкод идентифицирует состояние фильтра
 	@Override
 	public int hashCode() { // https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#hashCode--
 		return idDeal;
 	}
 	
// вызывается из equals() грид-обёртки GridData
 	@Override
 	public boolean equals(Object obj) { // https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#equals-java.lang.Object-
 		if (this == obj)
 			return true;
 		if (obj == null)
 			return false;
 		if (!(obj instanceof DealLastState))
 			return false;
 		DealLastState other = (DealLastState) obj;
 		if (!this.idDeal.equals(other.idDeal)) // this.idDeal != other.idDeal // getIdDeal()
 			return false;
 		return true;
 	} // public boolean equals(Object obj)
    
	@Override
	public int compareTo(DealLastState obj) {
		if (this == obj)
			return 0;
		if (obj == null) {
			logger.error("null parameter in DealLastState.comparTo. this = {}", this);
			throw new NullPointerException("null parameter in DealLastState.comparTo. this = "+this);
		}
		//return this.idDeal == obj.idDeal ? 0 : this.idDeal > obj.idDeal ? 1 : -1;
		return this.idDeal.compareTo(obj.idDeal);
	} // public int compareTo(DealLastState obj)
	
	
	private static String[] pkNames = {"idDeal", "lmcpRowId"};
	/** Таблица названий полей Первичных Ключей, поддерживаемых бином.
	 * Например, для наполнения меню выбора ПК. Далее по выбранному названию получаем компаратор вызовом {@link #getPkComparatorByName(String)}.
	 * (Это часть статического интерфейса)
	 */
	public static String[] getPkNames() {
		return pkNames;
	}
	/** По названию поля ПК (одного из {@link #getPkNames()}) получить соответствующий Comparator<DealLastState> для сравнения по этому полю.
	 * @return null если поле не является ПК.
	 */
	public static Comparator<DealLastState> getPkComparatorByName(String namePk) {
    	switch (namePk) {
			case "idDeal": return getCompareByIdDeal();
			case "lmcpRowId": return getCompareByRowId();
//			case "clnId": return getCompareByClnId();
			case "rsubjId": return getCompareByRsubjId();
    	}
    	return null;
	}

	
	/** Возвращает компаратор по ПК idDeal. Единственный консистентен с hashCode, equals, compareTo. */
	// вызывается из class CompareByPK implements Comparator<GridData>, который задаётся совместно с PK в дата-провайдере и используется при сортировке и бинарном поиске объекта GridData
	public static Comparator<DealLastState> getCompareByIdDeal() {
		return DealLastState.CompareByIdDeal.compareByIdDeal;
	}
	
	/** Возвращает компаратор по искуственному ПК lmcpRowId (для тестирования). */
	public static Comparator<DealLastState> getCompareByRowId() {
		return DealLastState.CompareByRowId.compareByRowId;
	}
	
	/** Компаратор по ИД заёмщика (FK на список субъектов). */
	/*public static Comparator<DealLastState> getCompareByClnId() {
		return DealLastState.CompareByClnId.compareByClnId;
	}*/
	
	/** Компаратор по ИД СПР (FK на список субъектов). */
	public static Comparator<DealLastState> getCompareByRsubjId() {
		return DealLastState.CompareByRsubjId.compareByRsubjId;
	}
	
	
	private static final class CompareByIdDeal implements Comparator<DealLastState>, Serializable {
		private static final long serialVersionUID = -5276988424096642980L;
		public static final Comparator<DealLastState> compareByIdDeal = new CompareByIdDeal();
		public int compare(DealLastState o1, DealLastState o2) {
			if (o1 == null || o2 == null) {
				logger.error("DealLastState.CompareByIdDeal.compare. null parameter: o1 = {}, o2 = {}", o1, o2);
				throw new NullPointerException("DealLastState.CompareByIdDeal.compare. null parameter: o1 = " + o1 + ", o2 = " + o2);
			}
			//return o1.idDeal == o2.idDeal ? 0 : o1.idDeal > o2.idDeal ? 1 : -1; // int
			return o1.idDeal.compareTo(o2.idDeal); // Integer !!
		}
	}

	private static final class CompareByRowId implements Comparator<DealLastState>, Serializable {
		private static final long serialVersionUID = -8124688018107277250L;
		public static final Comparator<DealLastState> compareByRowId = new CompareByRowId();
		public int compare(DealLastState o1, DealLastState o2) {
			if (o1 == null || o2 == null) {
				logger.error("DealLastState.CompareByRowId.compare. null parameter: o1 = {}, o2 = {}", o1, o2);
				throw new NullPointerException("DealLastState.CompareByRowId.compare. null parameter: o1 = " + o1 + ", o2 = " + o2);
			}
			return o1.lmcpRowId.compareTo(o2.lmcpRowId);
		}
	}
	
	/*private static final class CompareByClnId implements Comparator<DealLastState>, Serializable {
		private static final long serialVersionUID = 3539136223419257105L;
		public static final Comparator<DealLastState> compareByClnId = new CompareByClnId();
		public int compare(DealLastState o1, DealLastState o2) {
			if (o1 == null || o2 == null) {
				logger.error("DealLastState.CompareByClnId.compare. null parameter: o1 = {}, o2 = {}", o1, o2);
				throw new NullPointerException("DealLastState.CompareByClnId.compare. null parameter: o1 = " + o1 + ", o2 = " + o2);
			}
			return o1.clnId.compareTo(o2.clnId);
		}
	}*/
	
	private static final class CompareByRsubjId implements Comparator<DealLastState>, Serializable {
		private static final long serialVersionUID = -854538292107369416L;
		public static final Comparator<DealLastState> compareByRsubjId = new CompareByRsubjId();
		public int compare(DealLastState o1, DealLastState o2) {
			if (o1 == null || o2 == null) {
				logger.error("DealLastState.CompareByRsubjId.compare. null parameter: o1 = {}, o2 = {}", o1, o2);
				throw new NullPointerException("DealLastState.CompareByRsubjId.compare. null parameter: o1 = " + o1 + ", o2 = " + o2);
			}
			return o1.rsubjId.compareTo(o2.rsubjId);
		}
	}
	
} // public class DealLastState implements Serializable, Comparable<DealLastState>