package basos.xe.data.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;
import java.util.Comparator;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


/** Entity class "все транши (только дочерние к рамкам, без самостоятельных кредитов/гарантий) из последнего среза
 *  с остатками", обёртываемый в GridData для использования в гриде/листбоксе.
 * RULE: все приватные нестатические поля доменного объекта класс beanClass должны относиться к полям данных.
 * Метод {@link #getPkMap()} - часть статического интерфейса.
 */
public class TrancheLastState implements Serializable, Comparable<TrancheLastState> {
	
	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.idDeal
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private Integer idDeal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.idParent
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private Integer idParent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.ddRest
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private Date ddRest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.balType
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private String balType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.prodType
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private String prodType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.clnId
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private Integer clnId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.rsubjId
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private Integer rsubjId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.dogNum
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private String dogNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.trDogNum
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private String trDogNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.dbegin
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private Date dbegin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.dend
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private Date dend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.ddealClose
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private Date ddealClose;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.days
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private Integer days;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.ydur
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private BigDecimal ydur;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.dgvrCur
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private String dgvrCur;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.dgvrSum
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private BigDecimal dgvrSum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.dgvrSumUSD
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private BigDecimal dgvrSumUSD;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.perc
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private BigDecimal perc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.percKind
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private String percKind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.fondRate
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private BigDecimal fondRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.riskAddRate
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private BigDecimal riskAddRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.mrashRate
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private BigDecimal mrashRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.grOd
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private String grOd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.grPerc
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private String grPerc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.prodVar
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private String prodVar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.prodGr
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private String prodGr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.prodGoal
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private String prodGoal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.idReqZipKk
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private Integer idReqZipKk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.flg312p
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private String flg312p;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.dep
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private String dep;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.depFio
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private String depFio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.kbe
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private String kbe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.kbeFio
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private String kbeFio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.isSmeDeal
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private Boolean isSmeDeal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_TRANCHES_LAST_STATE.lmcpRowId
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    private String lmcpRowId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_TRANCHES_LAST_STATE
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public TrancheLastState(Integer idDeal, Integer idParent, Date ddRest, String balType, String prodType, Integer clnId, Integer rsubjId, String dogNum, String trDogNum, Date dbegin, Date dend, Date ddealClose, Integer days, BigDecimal ydur, String dgvrCur, BigDecimal dgvrSum, BigDecimal dgvrSumUSD, BigDecimal perc, String percKind, BigDecimal fondRate, BigDecimal riskAddRate, BigDecimal mrashRate, String grOd, String grPerc, String prodVar, String prodGr, String prodGoal, Integer idReqZipKk, String flg312p, String dep, String depFio, String kbe, String kbeFio, Boolean isSmeDeal, String lmcpRowId) {
        this.idDeal = idDeal;
        this.idParent = idParent;
        this.ddRest = ddRest;
        this.balType = balType;
        this.prodType = prodType;
        this.clnId = clnId;
        this.rsubjId = rsubjId;
        this.dogNum = dogNum;
        this.trDogNum = trDogNum;
        this.dbegin = dbegin;
        this.dend = dend;
        this.ddealClose = ddealClose;
        this.days = days;
        this.ydur = ydur;
        this.dgvrCur = dgvrCur;
        this.dgvrSum = dgvrSum;
        this.dgvrSumUSD = dgvrSumUSD;
        this.perc = perc;
        this.percKind = percKind;
        this.fondRate = fondRate;
        this.riskAddRate = riskAddRate;
        this.mrashRate = mrashRate;
        this.grOd = grOd;
        this.grPerc = grPerc;
        this.prodVar = prodVar;
        this.prodGr = prodGr;
        this.prodGoal = prodGoal;
        this.idReqZipKk = idReqZipKk;
        this.flg312p = flg312p;
        this.dep = dep;
        this.depFio = depFio;
        this.kbe = kbe;
        this.kbeFio = kbeFio;
        this.isSmeDeal = isSmeDeal;
        this.lmcpRowId = lmcpRowId;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.idDeal
     *
     * @return the value of MV_TRANCHES_LAST_STATE.idDeal
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public Integer getIdDeal() {
        return idDeal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.idDeal
     *
     * @param idDeal the value for MV_TRANCHES_LAST_STATE.idDeal
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setIdDeal(Integer idDeal) {
        this.idDeal = idDeal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.idParent
     *
     * @return the value of MV_TRANCHES_LAST_STATE.idParent
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public Integer getIdParent() {
        return idParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.idParent
     *
     * @param idParent the value for MV_TRANCHES_LAST_STATE.idParent
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setIdParent(Integer idParent) {
        this.idParent = idParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.ddRest
     *
     * @return the value of MV_TRANCHES_LAST_STATE.ddRest
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public Date getDdRest() {
        return ddRest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.ddRest
     *
     * @param ddRest the value for MV_TRANCHES_LAST_STATE.ddRest
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setDdRest(Date ddRest) {
        this.ddRest = ddRest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.balType
     *
     * @return the value of MV_TRANCHES_LAST_STATE.balType
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public String getBalType() {
        return balType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.balType
     *
     * @param balType the value for MV_TRANCHES_LAST_STATE.balType
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setBalType(String balType) {
        this.balType = balType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.prodType
     *
     * @return the value of MV_TRANCHES_LAST_STATE.prodType
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public String getProdType() {
        return prodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.prodType
     *
     * @param prodType the value for MV_TRANCHES_LAST_STATE.prodType
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setProdType(String prodType) {
        this.prodType = prodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.clnId
     *
     * @return the value of MV_TRANCHES_LAST_STATE.clnId
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public Integer getClnId() {
        return clnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.clnId
     *
     * @param clnId the value for MV_TRANCHES_LAST_STATE.clnId
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setClnId(Integer clnId) {
        this.clnId = clnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.rsubjId
     *
     * @return the value of MV_TRANCHES_LAST_STATE.rsubjId
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public Integer getRsubjId() {
        return rsubjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.rsubjId
     *
     * @param rsubjId the value for MV_TRANCHES_LAST_STATE.rsubjId
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setRsubjId(Integer rsubjId) {
        this.rsubjId = rsubjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.dogNum
     *
     * @return the value of MV_TRANCHES_LAST_STATE.dogNum
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public String getDogNum() {
        return dogNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.dogNum
     *
     * @param dogNum the value for MV_TRANCHES_LAST_STATE.dogNum
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setDogNum(String dogNum) {
        this.dogNum = dogNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.trDogNum
     *
     * @return the value of MV_TRANCHES_LAST_STATE.trDogNum
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public String getTrDogNum() {
        return trDogNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.trDogNum
     *
     * @param trDogNum the value for MV_TRANCHES_LAST_STATE.trDogNum
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setTrDogNum(String trDogNum) {
        this.trDogNum = trDogNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.dbegin
     *
     * @return the value of MV_TRANCHES_LAST_STATE.dbegin
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public Date getDbegin() {
        return dbegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.dbegin
     *
     * @param dbegin the value for MV_TRANCHES_LAST_STATE.dbegin
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setDbegin(Date dbegin) {
        this.dbegin = dbegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.dend
     *
     * @return the value of MV_TRANCHES_LAST_STATE.dend
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public Date getDend() {
        return dend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.dend
     *
     * @param dend the value for MV_TRANCHES_LAST_STATE.dend
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setDend(Date dend) {
        this.dend = dend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.ddealClose
     *
     * @return the value of MV_TRANCHES_LAST_STATE.ddealClose
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public Date getDdealClose() {
        return ddealClose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.ddealClose
     *
     * @param ddealClose the value for MV_TRANCHES_LAST_STATE.ddealClose
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setDdealClose(Date ddealClose) {
        this.ddealClose = ddealClose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.days
     *
     * @return the value of MV_TRANCHES_LAST_STATE.days
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public Integer getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.days
     *
     * @param days the value for MV_TRANCHES_LAST_STATE.days
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setDays(Integer days) {
        this.days = days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.ydur
     *
     * @return the value of MV_TRANCHES_LAST_STATE.ydur
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public BigDecimal getYdur() {
        return ydur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.ydur
     *
     * @param ydur the value for MV_TRANCHES_LAST_STATE.ydur
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setYdur(BigDecimal ydur) {
        this.ydur = ydur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.dgvrCur
     *
     * @return the value of MV_TRANCHES_LAST_STATE.dgvrCur
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public String getDgvrCur() {
        return dgvrCur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.dgvrCur
     *
     * @param dgvrCur the value for MV_TRANCHES_LAST_STATE.dgvrCur
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setDgvrCur(String dgvrCur) {
        this.dgvrCur = dgvrCur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.dgvrSum
     *
     * @return the value of MV_TRANCHES_LAST_STATE.dgvrSum
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public BigDecimal getDgvrSum() {
        return dgvrSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.dgvrSum
     *
     * @param dgvrSum the value for MV_TRANCHES_LAST_STATE.dgvrSum
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setDgvrSum(BigDecimal dgvrSum) {
        this.dgvrSum = dgvrSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.dgvrSumUSD
     *
     * @return the value of MV_TRANCHES_LAST_STATE.dgvrSumUSD
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public BigDecimal getDgvrSumUSD() {
        return dgvrSumUSD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.dgvrSumUSD
     *
     * @param dgvrSumUSD the value for MV_TRANCHES_LAST_STATE.dgvrSumUSD
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setDgvrSumUSD(BigDecimal dgvrSumUSD) {
        this.dgvrSumUSD = dgvrSumUSD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.perc
     *
     * @return the value of MV_TRANCHES_LAST_STATE.perc
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public BigDecimal getPerc() {
        return perc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.perc
     *
     * @param perc the value for MV_TRANCHES_LAST_STATE.perc
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setPerc(BigDecimal perc) {
        this.perc = perc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.percKind
     *
     * @return the value of MV_TRANCHES_LAST_STATE.percKind
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public String getPercKind() {
        return percKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.percKind
     *
     * @param percKind the value for MV_TRANCHES_LAST_STATE.percKind
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setPercKind(String percKind) {
        this.percKind = percKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.fondRate
     *
     * @return the value of MV_TRANCHES_LAST_STATE.fondRate
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public BigDecimal getFondRate() {
        return fondRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.fondRate
     *
     * @param fondRate the value for MV_TRANCHES_LAST_STATE.fondRate
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setFondRate(BigDecimal fondRate) {
        this.fondRate = fondRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.riskAddRate
     *
     * @return the value of MV_TRANCHES_LAST_STATE.riskAddRate
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public BigDecimal getRiskAddRate() {
        return riskAddRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.riskAddRate
     *
     * @param riskAddRate the value for MV_TRANCHES_LAST_STATE.riskAddRate
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setRiskAddRate(BigDecimal riskAddRate) {
        this.riskAddRate = riskAddRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.mrashRate
     *
     * @return the value of MV_TRANCHES_LAST_STATE.mrashRate
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public BigDecimal getMrashRate() {
        return mrashRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.mrashRate
     *
     * @param mrashRate the value for MV_TRANCHES_LAST_STATE.mrashRate
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setMrashRate(BigDecimal mrashRate) {
        this.mrashRate = mrashRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.grOd
     *
     * @return the value of MV_TRANCHES_LAST_STATE.grOd
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public String getGrOd() {
        return grOd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.grOd
     *
     * @param grOd the value for MV_TRANCHES_LAST_STATE.grOd
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setGrOd(String grOd) {
        this.grOd = grOd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.grPerc
     *
     * @return the value of MV_TRANCHES_LAST_STATE.grPerc
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public String getGrPerc() {
        return grPerc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.grPerc
     *
     * @param grPerc the value for MV_TRANCHES_LAST_STATE.grPerc
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setGrPerc(String grPerc) {
        this.grPerc = grPerc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.prodVar
     *
     * @return the value of MV_TRANCHES_LAST_STATE.prodVar
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public String getProdVar() {
        return prodVar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.prodVar
     *
     * @param prodVar the value for MV_TRANCHES_LAST_STATE.prodVar
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setProdVar(String prodVar) {
        this.prodVar = prodVar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.prodGr
     *
     * @return the value of MV_TRANCHES_LAST_STATE.prodGr
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public String getProdGr() {
        return prodGr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.prodGr
     *
     * @param prodGr the value for MV_TRANCHES_LAST_STATE.prodGr
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setProdGr(String prodGr) {
        this.prodGr = prodGr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.prodGoal
     *
     * @return the value of MV_TRANCHES_LAST_STATE.prodGoal
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public String getProdGoal() {
        return prodGoal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.prodGoal
     *
     * @param prodGoal the value for MV_TRANCHES_LAST_STATE.prodGoal
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setProdGoal(String prodGoal) {
        this.prodGoal = prodGoal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.idReqZipKk
     *
     * @return the value of MV_TRANCHES_LAST_STATE.idReqZipKk
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public Integer getIdReqZipKk() {
        return idReqZipKk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.idReqZipKk
     *
     * @param idReqZipKk the value for MV_TRANCHES_LAST_STATE.idReqZipKk
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setIdReqZipKk(Integer idReqZipKk) {
        this.idReqZipKk = idReqZipKk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.flg312p
     *
     * @return the value of MV_TRANCHES_LAST_STATE.flg312p
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public String getFlg312p() {
        return flg312p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.flg312p
     *
     * @param flg312p the value for MV_TRANCHES_LAST_STATE.flg312p
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setFlg312p(String flg312p) {
        this.flg312p = flg312p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.dep
     *
     * @return the value of MV_TRANCHES_LAST_STATE.dep
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public String getDep() {
        return dep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.dep
     *
     * @param dep the value for MV_TRANCHES_LAST_STATE.dep
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setDep(String dep) {
        this.dep = dep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.depFio
     *
     * @return the value of MV_TRANCHES_LAST_STATE.depFio
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public String getDepFio() {
        return depFio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.depFio
     *
     * @param depFio the value for MV_TRANCHES_LAST_STATE.depFio
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setDepFio(String depFio) {
        this.depFio = depFio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.kbe
     *
     * @return the value of MV_TRANCHES_LAST_STATE.kbe
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public String getKbe() {
        return kbe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.kbe
     *
     * @param kbe the value for MV_TRANCHES_LAST_STATE.kbe
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setKbe(String kbe) {
        this.kbe = kbe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.kbeFio
     *
     * @return the value of MV_TRANCHES_LAST_STATE.kbeFio
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public String getKbeFio() {
        return kbeFio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.kbeFio
     *
     * @param kbeFio the value for MV_TRANCHES_LAST_STATE.kbeFio
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setKbeFio(String kbeFio) {
        this.kbeFio = kbeFio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.isSmeDeal
     *
     * @return the value of MV_TRANCHES_LAST_STATE.isSmeDeal
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public Boolean getIsSmeDeal() {
        return isSmeDeal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.isSmeDeal
     *
     * @param isSmeDeal the value for MV_TRANCHES_LAST_STATE.isSmeDeal
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setIsSmeDeal(Boolean isSmeDeal) {
        this.isSmeDeal = isSmeDeal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_TRANCHES_LAST_STATE.lmcpRowId
     *
     * @return the value of MV_TRANCHES_LAST_STATE.lmcpRowId
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public String getLmcpRowId() {
        return lmcpRowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_TRANCHES_LAST_STATE.lmcpRowId
     *
     * @param lmcpRowId the value for MV_TRANCHES_LAST_STATE.lmcpRowId
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    public void setLmcpRowId(String lmcpRowId) {
        this.lmcpRowId = lmcpRowId;
    }

// см. toString в одну строку: ReflectionToStringBuilder.toString(this, ToStringStyle.MULTI_LINE_STYLE)
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_TRANCHES_LAST_STATE
     *
     * @mbg.generated Sat Feb 25 17:28:33 MSK 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idDeal=").append(idDeal);
        sb.append(", idParent=").append(idParent);
        sb.append(", ddRest=").append(ddRest);
        sb.append(", balType=").append(balType);
        sb.append(", prodType=").append(prodType);
        sb.append(", clnId=").append(clnId);
        sb.append(", rsubjId=").append(rsubjId);
        sb.append(", dogNum=").append(dogNum);
        sb.append(", trDogNum=").append(trDogNum);
        sb.append(", dbegin=").append(dbegin);
        sb.append(", dend=").append(dend);
        sb.append(", ddealClose=").append(ddealClose);
        sb.append(", days=").append(days);
        sb.append(", ydur=").append(ydur);
        sb.append(", dgvrCur=").append(dgvrCur);
        sb.append(", dgvrSum=").append(dgvrSum);
        sb.append(", dgvrSumUSD=").append(dgvrSumUSD);
        sb.append(", perc=").append(perc);
        sb.append(", percKind=").append(percKind);
        sb.append(", fondRate=").append(fondRate);
        sb.append(", riskAddRate=").append(riskAddRate);
        sb.append(", mrashRate=").append(mrashRate);
        sb.append(", grOd=").append(grOd);
        sb.append(", grPerc=").append(grPerc);
        sb.append(", prodVar=").append(prodVar);
        sb.append(", prodGr=").append(prodGr);
        sb.append(", prodGoal=").append(prodGoal);
        sb.append(", idReqZipKk=").append(idReqZipKk);
        sb.append(", flg312p=").append(flg312p);
        sb.append(", dep=").append(dep);
        sb.append(", depFio=").append(depFio);
        sb.append(", kbe=").append(kbe);
        sb.append(", kbeFio=").append(kbeFio);
        sb.append(", isSmeDeal=").append(isSmeDeal);
        sb.append(", lmcpRowId=").append(lmcpRowId);
        sb.append("]");
        return sb.toString();
    }
    
	/** RULE: конструктор по умолчанию генерит тестовые данные. */
// !!! MyBatis-generator генерит свой пустой безаргументный конструктор с опцией generatorConfiguration.context.table.constructorBased !!!
 	public TrancheLastState() {
 	} // no-arg constructor of mock object
 	
 	private static final long serialVersionUID = -5898646810710651183L;
 	
	private static final Logger logger = LoggerFactory.getLogger(TrancheLastState.class);
	
    public static long getSerialVersionUID() {
		return serialVersionUID;
	}
    
// (вызывается из hashCode() грид-обёртки GridData) для списка объектов хэшкод идентифицирует состояние фильтра
 	@Override
 	public int hashCode() { // https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#hashCode--
 		return idDeal;
 	}
 	
// вызывается из equals() грид-обёртки GridData
 	@Override
 	public boolean equals(Object obj) { // https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#equals-java.lang.Object-
 		if (this == obj)
 			return true;
 		if (obj == null)
 			return false;
 		if (!(obj instanceof TrancheLastState))
 			return false;
 		TrancheLastState other = (TrancheLastState) obj;
 		if (!this.idDeal.equals(other.idDeal)) // this.idDeal != other.idDeal // getIdDeal()
 			return false;
 		return true;
 	} // public boolean equals(Object obj)
    
	@Override
	public int compareTo(TrancheLastState obj) {
		if (this == obj)
			return 0;
		if (obj == null) {
			logger.error("null parameter in TrancheLastState.comparTo. this = {}", this);
			throw new NullPointerException("null parameter in TrancheLastState.comparTo. this = "+this);
		}
		//return this.idDeal == obj.idDeal ? 0 : this.idDeal > obj.idDeal ? 1 : -1;
		return this.idDeal.compareTo(obj.idDeal);
	} // public int compareTo(TrancheLastState obj)
	
	
	private static String[] pkNames = {"idDeal", "lmcpRowId"};
	/** Таблица названий полей Первичных Ключей, поддерживаемых бином.
	 * Например, для наполнения меню выбора ПК. Далее по выбранному названию получаем компаратор вызовом {@link #getPkComparatorByName(String)}.
	 * (Это часть статического интерфейса)
	 */
	public static String[] getPkNames() {
		return pkNames;
	}
	/** По названию поля ПК (одного из {@link #getPkNames()}) получить соответствующий Comparator<TrancheLastState> для сравнения по этому полю.
	 * @return null если поле не является ПК.
	 */
	public static Comparator<TrancheLastState> getPkComparatorByName(String namePk) {
    	switch (namePk) {
			case "idDeal": return getCompareByIdDeal();
			case "lmcpRowId": return getCompareByRowId();
			case "idParent": return getCompareByIdParent();
    	}
    	return null;
	}

	
	/** Возвращает компаратор по ПК idDeal. Единственный консистентен с hashCode, equals, compareTo. */
	// вызывается из class CompareByPK implements Comparator<GridData>, который задаётся совместно с PK в дата-провайдере и используется при сортировке и бинарном поиске объекта GridData
	public static Comparator<TrancheLastState> getCompareByIdDeal() {
		return TrancheLastState.CompareByIdDeal.compareByIdDeal;
	}
	/** Возвращает компаратор по искуственному ПК lmcpRowId (для тестирования). */
	public static Comparator<TrancheLastState> getCompareByRowId() {
		return TrancheLastState.CompareByRowId.compareByRowId;
	}
	
	private static final class CompareByIdDeal implements Comparator<TrancheLastState>, Serializable {
		private static final long serialVersionUID = -3676847037307206779L;
		public static final Comparator<TrancheLastState> compareByIdDeal = new CompareByIdDeal();
		public int compare(TrancheLastState o1, TrancheLastState o2) {
			if (o1 == null || o2 == null) {
				logger.error("TrancheLastState.CompareByIdDeal.compare. null parameter: o1 = {}, o2 = {}", o1, o2);
				throw new NullPointerException("TrancheLastState.CompareByIdDeal.compare. null parameter: o1 = " + o1 + ", o2 = " + o2);
			}
			//return o1.idDeal == o2.idDeal ? 0 : o1.idDeal > o2.idDeal ? 1 : -1;
			return o1.idDeal.compareTo(o2.idDeal); // Integer !!!
		}
	}

	private static final class CompareByRowId implements Comparator<TrancheLastState>, Serializable {
		private static final long serialVersionUID = 262113994763278697L;
		public static final Comparator<TrancheLastState> compareByRowId = new CompareByRowId();
		public int compare(TrancheLastState o1, TrancheLastState o2) {
			if (o1 == null || o2 == null) {
				logger.error("TrancheLastState.CompareByRowId.compare. null parameter: o1 = {}, o2 = {}", o1, o2);
				throw new NullPointerException("TrancheLastState.CompareByRowId.compare. null parameter: o1 = " + o1 + ", o2 = " + o2);
			}
			return o1.lmcpRowId.compareTo(o2.lmcpRowId);
		}
	}
	
	
	public static Comparator<TrancheLastState> getCompareByIdParent() {
		return TrancheLastState.CompareByIdParent.compareByIdParent;
	}
	
	private static final class CompareByIdParent implements Comparator<TrancheLastState>, Serializable {
		private static final long serialVersionUID = -3676847037307206779L;
		public static final Comparator<TrancheLastState> compareByIdParent = new CompareByIdParent();
		public int compare(TrancheLastState o1, TrancheLastState o2) {
			if (o1 == null || o2 == null) {
				logger.error("TrancheLastState.CompareByIdParent.compare. null parameter: o1 = {}, o2 = {}", o1, o2);
				throw new NullPointerException("TrancheLastState.CompareByIdParent.compare. null parameter: o1 = " + o1 + ", o2 = " + o2);
			}
			//return o1.idParent == o2.idParent ? 0 : o1.idParent > o2.idParent ? 1 : -1;
			return o1.idParent.compareTo(o2.idParent); // Integer !!!
		}
	}
	
} // public class TrancheLastState implements Serializable, Comparable<TrancheLastState>